module LitPro

export LitCell, parse_cells, run_litpro, export_litpro, html_litpro, @litpro

struct LitCell
    id::String
    dependencies::Vector{String}
    code::String
end

const CELL_PATTERN = r"<!--\s*cell:([^\s>]+)(?:\s+depends:([^\s>]+))?\s*-->\s*```julia[^\n]*\n(.*?)```"s

function parse_cells(content::AbstractString)
    cells = LitCell[]
    seen = Set{String}()

    for m in eachmatch(CELL_PATTERN, content)
        id = String(m.captures[1])
        id in seen && error("duplicate LitPro cell: $id")
        push!(seen, id)

        deps_capture = m.captures[2]
        dependencies = deps_capture === nothing ? String[] :
            filter(!isempty, strip.(split(String(deps_capture), ',')))
        code = String(m.captures[3])
        push!(cells, LitCell(id, dependencies, code))
    end

    return cells
end

function _execution_order(cells::Vector{LitCell})
    by_id = Dict(cell.id => cell for cell in cells)
    visiting = Set{String}()
    visited = Set{String}()
    ordered = LitCell[]

    function visit(id::String)
        id in visited && return
        haskey(by_id, id) || error("unknown LitPro dependency: $id")
        id in visiting && error("cyclic LitPro dependency involving: $id")

        push!(visiting, id)
        cell = by_id[id]
        for dependency in cell.dependencies
            visit(dependency)
        end
        delete!(visiting, id)
        push!(visited, id)
        push!(ordered, cell)
    end

    for cell in cells
        visit(cell.id)
    end

    return ordered
end

function _read_cells(filename::AbstractString)
    content = read(filename, String)
    cells = parse_cells(content)
    isempty(cells) && error("no Julia LitPro cells found in $filename")
    return _execution_order(cells)
end

function run_litpro(filename::AbstractString)
    runtime = Module(Symbol("LitProRuntime_", string(time_ns())))
    for cell in _read_cells(filename)
        Base.include_string(runtime, cell.code, string(filename, "#", cell.id))
    end
    return runtime
end

function export_litpro(filename::AbstractString, output_file::AbstractString)
    cells = _read_cells(filename)
    open(output_file, "w") do io
        println(io, "# Generated by LitPro.jl from $(basename(filename))")
        for cell in cells
            println(io, "\n# --- cell:$(cell.id) ---")
            write(io, cell.code)
            endswith(cell.code, "\n") || println(io)
        end
    end
    return output_file
end

function _escape_html(text::AbstractString)
    escaped = replace(String(text), '&' => "&amp;")
    escaped = replace(escaped, '<' => "&lt;")
    escaped = replace(escaped, '>' => "&gt;")
    return escaped
end

function html_litpro(filename::AbstractString, output_file::AbstractString)
    cells = _read_cells(filename)
    open(output_file, "w") do io
        println(io, "<!doctype html>")
        println(io, "<html><head><meta charset=\"utf-8\"><title>",
                _escape_html(basename(filename)), "</title></head><body>")
        println(io, "<h1>", _escape_html(basename(filename)), "</h1>")
        for cell in cells
            println(io, "<section><h2>", _escape_html(cell.id), "</h2>")
            if !isempty(cell.dependencies)
                println(io, "<p>Depends on: ",
                        _escape_html(join(cell.dependencies, ", ")), "</p>")
            end
            println(io, "<pre><code class=\"language-julia\">",
                    _escape_html(cell.code), "</code></pre></section>")
        end
        println(io, "</body></html>")
    end
    return output_file
end

macro litpro(filename)
    return :(run_litpro($(esc(filename))))
end

end
